### ISSUE TITLE
Sharepoint upload specific folder or file (e.g, .apk file)

### ISSUE THREAD

**Issue by spurdow** [obrassard/action-sharepoint-publish#12]
To start ~  A big thanks to the library !! 
I am starting off to learn how to create and market github-actions specifically app (android / iOS) related.

Though I am a bit stuck because it will archive all the repo and It seems my requirements requires only the .apk file or .ipa file.

Is there any future support for the above mentioned items?

And once again a big thanks to the library and its author !!

**Comment by obrassard** [comment]
Hello ! Thank you for your feedback. 

Unfortunately, it's not in my plans to update this action at the moment, mainly because of lack of time (I use most of my free time to maintain other/larger projects.) However, it shouldn't be too complicated to update the current code in order to achieve what you want !

I invite you to fork the project and give it a try ! Most of the logic is located in `index.js` and `entrypoint.sh`.

The script shell runs before the `index.js` file. In the current implementation, the script Zip the content of the repository, and the JS file is responsible of uploading the archive to Sharepoint using the `spsave` module. A few changes to these files should be enough to do what you want 👍 

I hope this can help you!

**Comment by obrassard** [comment]
It is now possible to upload a single file instead of the whole repository, with the `file_path` option.

Available on v1.1.0
